# Generated by Django 5.2.6 on 2025-09-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_transport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='destination',
        ),
        migrations.AddField(
            model_name='transport',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
