# Generated by Django 5.2.6 on 2025-09-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_touristplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristplace',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='touristplace',
            name='image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='touristplace',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='touristplace',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
