# Generated by Django 5.2.6 on 2025-09-16 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_touristplace_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristplace',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_places', to='core.touristplace'),
        ),
    ]
